name: tugas_uas
description: "A new Flutter project."
publish_to: 'none'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.13
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: ^1.2.1

environment:
  sdk: '^3.4.0'
flutter:
  uses-material-design: true
  assets:
    - assets/pahlawan_nasional.json


